version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/graphql-fusion
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: yarn install
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: test
          command: yarn jest --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  deploy:
      docker:
        - image: circleci/node:8.9.4
      working_directory: ~/graphql-fusion
      steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
        - run:
            name: Install NPM token
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Deploy if tests pass and branch is Master
            command: npm publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/